config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#index'



  namespace :users do
    resources :notes do
      resource :likes, only: [:create, :destroy]
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence:true
  validates :body, presence:true
  belongs_to :user
  has_many :likes
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

         def self.from_omniauth(auth)
         where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
           user.email = auth.info.email
           user.password = Devise.friendly_token[0,20]
           #user.name = auth.info.name   # assuming the user model has a name
           #user.image = auth.info.image # assuming the user model has an image
           # If you are using confirmable and the provider(s) you use validate emails,
           # uncomment the line below to skip the confirmation emails.
           # user.skip_confirmation!
         end
       end
  has_many :notes
  has_many :likes

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followees, through: :active_relationships

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followee_id
  has_many :followers, through: :passive_relationships

  def like(note)
    likes.create(note_id: note.id)
  end

  def likes?(note)
    likes.exists?(note_id: note.id)
  end

  def follow(user)
    followees << user if !self.following?(user) && self != user
  end

  def unfollow(user)
    followees.delete(user)
  end

  def following?(user)
    followees.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
    @note = Note.new
  end

  def new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      flash[:notice] = "Note is added!"
      redirect_to notes_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      flash[:notice] = "Note have been changed!"
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    flash[:alert] = "Deletion completed!!"
    redirect_to notes_path



  end

  private
  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @notes = Note.all
    @users = User.all
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followee_id])
    current_user.follow(user)
    redirect_to root_path
  end

  def destroy
    current_user.unfollow(params[:id])
    redirect_to root_path
  end
end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note

  def create
    note = Note.find(params[:note_id])
        current_user.like(note)
        UserMailer.send_like(note.user, note).deliver_later
        redirect_to users_notes_path

  end

  def destroy
    @like = Like.find_by(user_id: current_user.id)
    @like.destroy
    UserMailer.send_unlike(@note.user, @note).deliver_later
    redirect_to users_notes_path
  end

  private

    def set_note
      @note = Note.find(params[:note_id])
    end
end

app/controllers/users/notes_controller.rb
class Users::NotesController < ApplicationController
  before_action :authenticate_user!
  def index
    @notes = current_user.notes.all
    @note = Note.new
  end

  def new
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      flash[:notice] = "Note is added!"
      redirect_to users_notes_path
    else
      redirect_to users_notes_path
    end
  end

  def show
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      flash[:notice] = "Note have been changed!"
      redirect_to users_notes_path
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    flash[:alert] = "Deletion completed!!"
    redirect_to users_notes_path



  end

  private
  def note_params
    params.require(:note).permit(:title, :body, :user_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAcFinalAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_new.html.slim
hr
.container
  h3 Making a new note
  .container
  = simple_form_for @note do |f|
    = f.input :title, label: false , placeholder: "Title name "
    = f.input :body, label: false , placeholder: "What do you want to say "
    = f.button :submit, :label =>"Save", :class => "btn btn-outline-info"
    - if flash[:notice]
      a.notice
        |  =
        = flash[:notice]
        |  =

app/views/notes/edit.html.slim
hr
h1
 |Note Editor
.container
  h3= @note.title
  .container
  = simple_form_for @note, url: note_path, method: :put do |f|
    = f.input :title, label: false
    = f.input :body, label: false
    = f.button :submit, :label =>"Save", :class => "btn btn-outline-info"
    - if flash[:notice]
      a.notice
        |  =
        = flash[:notice]
        |  =
  p
  h4= link_to 'Back to your notes', notes_path

app/views/pages/index.html.slim
h1 Pages#index
p Find me in app/views/pages/index.html.slim

.container
  -if user_signed_in?
    = link_to 'See my notes',users_notes_path
    br
    btn
      = link_to 'Log Out', destroy_user_session_path, method: :delete, :class => "btn btn-outline-danger"
  -else
    btn
      = link_to "User Sign In", new_user_session_path, class:"nav-item nav-link btn btn-info btn-sm"
  .container

      -@notes.each do |note|
        ul

        h3=note.title
        p=note.body
        -if user_signed_in? && current_user.likes?(note)
          = link_to 'UNLIKE', users_note_likes_path(note), method: :delete
        -else
          = link_to 'LIKE', users_note_likes_path(note), method: :post
-if user_signed_in?
  .container
    -@users.each do |user|
      ul
        -unless current_user == user
          =user.email
          - unless current_user.following?(user)
            =form_for (current_user.active_relationships.build) do |f|
              = hidden_field_tag :followee_id, user.id
              =f.submit "Follow", class: "btn btn-primary"
          br
          = link_to 'Unfollow', relationship_path(user), method: :delete, class: "btn btn-danger" if current_user.following?(user)

app/views/users/notes/_likes.html.erb
<div>
<% if user_signed_in? && current_user.likes?(note)%>
  <%# todo soon: unlike button form %>
<% else %>
  <%= link_to 'LIKE', users_note_likes_path, method: :post %>


<% end %>
</div>

app/views/users/notes/_new.html.slim
hr
.container
  h3 Making a new note
  .container
  = simple_form_for @note, url: users_notes_path do |f|
    = f.input :title, label: false , placeholder: "Title name "
    = f.input :body, label: false , placeholder: "What do you want to say "
    = f.button :submit, :label =>"Save", :class => "btn btn-outline-info"
    - if flash[:notice]
      a.notice
        |  =
        = flash[:notice]
        |  =

app/views/users/notes/edit.html.slim
hr
h1
 |Note Editor
 = link_to 'Log Out', destroy_user_session_path, method: :delete, :class => "btn btn-outline-danger"
.container
  h3= @note.title
  .container
  = simple_form_for @note, url: users_note_path, method: :put do |f|
    = f.input :title, label: false
    = f.input :body, label: false
    = f.button :submit, :label =>"Save", :class => "btn btn-outline-info"
    - if flash[:notice]
      a.notice
        |  =
        = flash[:notice]
        |  =
  p
  h4= link_to 'Back to your notes', users_notes_path

app/views/users/notes/index.html.slim
h1 Notes#index
p Find me in app/views/notes/index.html.slim
= link_to 'Log Out', destroy_user_session_path, method: :delete, :class => "btn btn-outline-danger"
= link_to 'Dashboard', root_path
= render partial: 'new'

.container
  ul
    hr
    -@notes.each do |note|
      li
        h3=note.title
        p=note.body
        = link_to 'Edit', edit_users_note_path(note)
        br
        = link_to 'Delete', users_note_path(note), method: :delete, data:{confirm:"Are you sure?"}
        br
        -if user_signed_in? && current_user.likes?(note)
          = link_to 'UNLIKE', users_note_likes_path(note), method: :delete
        -else
          = link_to 'LIKE', users_note_likes_path(note), method: :post
        hr

app/views/users/notes/show.html.slim
h1 Notes#show
p Find me in app/views/notes/show.html.slim

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>